import { parseSimpleText,parseCSV,parseJSON,validateQuestions } from './importer.js';
import { listGames,saveGame,deleteGame,duplicateGame } from './storage.js';
import { S,$,$$,q,screen,toast } from './state-v2.js';

export async function library(startGame){screen('library');const games=await listGames(),box=$('#library-list');box.replaceChildren();$('#library-empty').classList.toggle('hidden',games.length>0);for(const g of games){const c=document.createElement('article');c.className='game-card';c.innerHTML='<h3></h3><div class="game-card-meta"></div><div class="game-card-actions"></div>';c.querySelector('h3').textContent=g.title;c.querySelector('.game-card-meta').textContent=`${g.questions.length} Fragen${g.updatedAt?` · geändert ${new Date(g.updatedAt).toLocaleDateString('de-CH')}`:''}`;const a=c.querySelector('.game-card-actions');a.append(button('Spielen','primary',()=>startGame(g)),button('Bearbeiten','',()=>openEditor(g)),button('Duplizieren','',async()=>{await duplicateGame(g.id);library(startGame);}),button('Löschen','',async()=>{if(confirm(`«${g.title}» wirklich löschen?`)){await deleteGame(g.id);library(startGame);}}));box.append(c);}}
function button(text,cls,fn){const b=document.createElement('button');b.className=`btn small ${cls}`;b.textContent=text;b.onclick=fn;return b;}

export function openEditor(g=null){S.editorId=g?.id??null;S.createdAt=g?.createdAt??null;S.editorQs=(g?.questions??[]).map(x=>({...x,id:x.id||crypto.randomUUID(),wrong:[...x.wrong]}));$('#game-title').value=g?.title??'';$('#editor-heading').textContent=g?'Spiel bearbeiten':'Neues Spiel';$('#simple-import').value='';$('#csv-import').value='';$('#json-import').value='';renderEditor();screen('editor');}
function sync(){const cards=$$('.question-card');if(!cards.length)return;S.editorQs=cards.map((c,i)=>({id:S.editorQs[i]?.id||crypto.randomUUID(),question:c.querySelector('[data-field="question"]').value.trim(),correct:c.querySelector('[data-field="correct"]').value.trim(),wrong:[0,1,2].map(n=>c.querySelector(`[data-field="wrong${n}"]`).value.trim())}));}
export function addQuestion(){sync();S.editorQs.push(q('','','','',''));renderEditor();}
function renderEditor(){const box=$('#question-list');box.replaceChildren();$('#question-count').textContent=S.editorQs.length;S.editorQs.forEach((x,i)=>{const f=$('#question-editor-template').content.cloneNode(true),c=f.querySelector('.question-card');c.querySelector('.question-number').textContent=`Frage ${i+1}`;c.querySelector('[data-field="question"]').value=x.question;c.querySelector('[data-field="correct"]').value=x.correct;[0,1,2].forEach(n=>c.querySelector(`[data-field="wrong${n}"]`).value=x.wrong[n]??'');c.querySelectorAll('[data-q-action]').forEach(b=>b.onclick=()=>{sync();const a=b.dataset.qAction;if(a==='delete')S.editorQs.splice(i,1);if(a==='up'&&i>0)[S.editorQs[i-1],S.editorQs[i]]=[S.editorQs[i],S.editorQs[i-1]];if(a==='down'&&i<S.editorQs.length-1)[S.editorQs[i+1],S.editorQs[i]]=[S.editorQs[i],S.editorQs[i+1]];renderEditor();});box.append(f);});}
function parse(){return S.importMode==='simple'?parseSimpleText($('#simple-import').value):S.importMode==='csv'?parseCSV($('#csv-import').value):parseJSON($('#json-import').value);}
export function doImport(){const arr=parse();if(!arr.length)throw Error('Keine Fragen erkannt.');sync();const replace=!S.editorQs.length||confirm(`${arr.length} Fragen erkannt. OK ersetzt die bisherigen Fragen, Abbrechen hängt sie an.`);S.editorQs=replace?arr:[...S.editorQs,...arr];renderEditor();toast(`${arr.length} Fragen übernommen.`);}
export function previewImport(){const a=parse();if(!a.length)throw Error('Keine Fragen erkannt.');alert(`${a.length} vollständige Fragen wurden erkannt.`);}
export function loadExample(){S.importMode='simple';$$('[data-import-tab]').forEach(x=>x.classList.toggle('active',x.dataset.importTab==='simple'));$$('[data-import-pane]').forEach(x=>x.classList.toggle('active',x.dataset.importPane==='simple'));$('#simple-import').value='Was versteht man unter Inflation?\nAnstieg des allgemeinen Preisniveaus\nRückgang der Arbeitslosigkeit\nZunahme des realen BIP\nSinkende Staatsausgaben\n\nWas ist ein Substitutionsgut zu Butter?\nMargarine\nBrot\nSalz\nMilch';}
export async function saveEditor(startGame){sync();const title=$('#game-title').value.trim();if(!title)throw Error('Bitte gib dem Spiel einen Titel.');const questions=validateQuestions(S.editorQs);if(!questions.length)throw Error('Das Spiel braucht mindestens eine vollständige Frage.');await saveGame({id:S.editorId||crypto.randomUUID(),createdAt:S.createdAt,title,questions});toast('Spiel gespeichert.');library(startGame);}
